[build]
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/139"
  to = "/.netlify/functions/auth"
  query = {drive = "139"}
  status = 200

# 通用规则：访问 /api/xxx 转发到函数
[[redirects]]
  from = "/api/:drive"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
